default_stages: [commit, push]

default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black

  - repo: https://github.com/csachs/pyproject-flake8
    rev: v0.0.1a3
    hooks:
    - id: pyproject-flake8
      additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    - id: mypy
      exclude: '(build/|examples/)'